site_name: Face Mask Detection
nav:
  - Setup: index.md
  - Custom Training: custom.md
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.sections
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iamrahul95
    - icon: fontawesome/brands/github
      link: https://github.com/Rahulgarg95
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rahulgarg95/
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
copyright: |
  &copy; 2021 <a href="https://github.com/Rahulgarg95"  target="_blank" rel="noopener">Rahul Garg</a>